os: osx
osx_image: xcode8.1

install:
  - cd runtime.osx.10.10-x64.CoreCompat.System.Drawing
  - wget https://download.microsoft.com/download/1/B/4/1B4DE605-8378-47A5-B01B-2C79D6C55519/dotnet-sdk-2.0.0-osx-x64.tar.gz -O dotnet-sdk-2.0.0-osx-x64.tar.gz
  - mkdir -p ~/dotnet/
  - tar xf dotnet-sdk-2.0.0-osx-x64.tar.gz -C ~/dotnet/
  - PATH="~/dotnet/:$PATH"
  - dotnet --version
  - ./get-sources.sh
  - ./install-dependencies.sh

script:
  - ./build.sh
  - dotnet build -c Release /p:VersionSuffix=r$TRAVIS_BUILD_NUMBER
  - dotnet pack -c Release /p:VersionSuffix=r$TRAVIS_BUILD_NUMBER
  - dotnet nuget push bin/Release/runtime.osx.10.10-x64.CoreCompat.System.Drawing.5.4.0-r$TRAVIS_BUILD_NUMBER.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_TOKEN
