variables:
  LIBGDIPLUS_VERSION: '5.8'

jobs:
- job: macos
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      brew install autoconf automake libtool pkg-config
    displayName: Install autotools
  - script: |
      cd runtime.osx.10.10-x64.CoreCompat.System.Drawing
      git clone https://github.com/corecompat/libgdiplus --depth 1 --single-branch --branch master
      brew install libtiff giflib libjpeg glib cairo freetype fontconfig libpng
    displayName: Download sources, install dependencies
  - script: |
      cd runtime.osx.10.10-x64.CoreCompat.System.Drawing

      # libffi is keg-only
      export LDFLAGS="-L/usr/local/opt/libffi/lib"
      export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

      ./build.sh
      mkdir ${BUILD_ARTIFACTSTAGINGDIRECTORY}/libgdiplus
      dotnet build -c Release /p:Version=${LIBGDIPLUS_VERSION}.${BUILD_BUILDID}
      dotnet pack -c Release /p:Version=${LIBGDIPLUS_VERSION}.${BUILD_BUILDID} -o ${BUILD_ARTIFACTSTAGINGDIRECTORY}/libgdiplus
    displayName: Build
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/libgdiplus'
      artifactName: 'libgdiplus'
      publishLocation: 'Container'
    displayName: Publish
    condition: always()
