name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macOS-10.15
    env:
      LIBGDIPLUS_VERSION: '6.0.5'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install autotools
        run: 
          brew install autoconf automake libtool pkg-config
      - name: Download sources, install dependencies
        run: |
          cd runtime.osx.10.10-x64.CoreCompat.System.Drawing
          git clone https://github.com/mono/libgdiplus --depth 1 --single-branch --branch ${LIBGDIPLUS_VERSION}
          brew install libtiff giflib libjpeg glib cairo freetype fontconfig libpng
      - name: Build
        run: |
          cd runtime.osx.10.10-x64.CoreCompat.System.Drawing

          # libffi is keg-only
          export LDFLAGS="-L/usr/local/opt/libffi/lib"
          export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

          ./build.sh
          mkdir ${{ github.workspace }}/bin/
          dotnet build -c Release /p:Version=${LIBGDIPLUS_VERSION}.${GITHUB_RUN_NUMBER}
          dotnet pack -c Release /p:Version=${LIBGDIPLUS_VERSION}.${GITHUB_RUN_NUMBER} -o ${{ github.workspace }}/bin/

      - name: Upload NuGet package
        uses: actions/upload-artifact@v2
        with:
          name: libgdiplus
          path: |
            ${{ github.workspace }}/bin/
